version: '2'
services:

  # The Application
  application:
    build:
      context: ./
      dockerfile: application.dockerfile
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www/html/
    volumes_from:
      - application
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=testdb"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test123"
      - "MYSQL_ROOT_PASSWORD=test123"
    ports:
        - "33061:3306"

volumes:
  dbdata:
